from .serializer_mixin import SwappableSerializerMixin
from .user import UserViewSet
from .cuenta import CuentaViewSet
from .movimiento import MovimientoViewSet
from .cierre import CierreViewSet
from .proyecto import ProyectoViewSet
from .categorias import CategoriasViewSet
from .reporteCf import ReporteCfViewSet
from .bodegas import BodegasViewSet
from .proveedor import ProveedorViewSet
from .productos import ProductosViewSet
from .compras import ComprasViewSet
from .movimiento_bodega import MovimientoBodegaViewSet
from .linea_produccion import LineaProduccionViewSet
from .inventario import InventarioViewSet
from .movimiento_granja import MovimientoGranjaViewSet
from .cliente import ClientesViewSet
from .ventas import VentasViewSet
from .reporte_bodega import ReporteBodegaViewSet