services:
  # Servicio de la base de datos MySQL
  db-mysql:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: borderless
      MYSQL_ROOT_PASSWORD: maysol123
      MYSQL_PORT: '3306'    
    ports:
      - "3306:3306"
    volumes:
      - mysql_datos:/var/lib/mysql
    networks:
      - mynetwork
  # Otros servicios de tu aplicación, como el servicio web
  maysol-django:
    container_name: maysol-django
    build: 
      context: ./maysol-back       
    command: gunicorn maysol.wsgi --bind  0.0.0.0:8000
      #python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/code    
    depends_on:
      - db-mysql     
    networks:
      - mynetwork 
# Servicio de phpMyAdmin
  phpmyadmin-maysol:
    container_name: phpmyadmin-maysol
    image: phpmyadmin/phpmyadmin
    platform: linux/x86_64
    environment:
      PMA_HOST: db-mysql
      MYSQL_ROOT_PASSWORD: maysol123
    ports:
      - "3000:80"    
    networks:
      - mynetwork
   # Servicio de react  
  front-redux:
    container_name: front-redux
    build: 
      context: ./maysol-front
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:      
      - ./maysol-front:/app
      - /app/node_modules
    networks:
      - mynetwork
   # Servicio de proxy   
  nginx-maysol:
    image: nginx:1.26.0
    platform: linux/x86_64
    ports:
     - "8081:80"
    volumes:
        - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro        
    depends_on:
      - maysol-django
      - front-redux  
    networks:
      - mynetwork    
      
volumes:
 mysql_datos:
networks:
  mynetwork:
    driver: bridge


  