# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-29 03:54
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', models.CharField(blank=True, max_length=120, null=True)),
                ('permisos', models.IntegerField(choices=[(20, 'SUPERADMIN'), (10, 'SUPERVISOR'), (5, 'BACKOFFICE'), (0, 'EMPLEADO')], default=10)),
                ('descripcion', models.CharField(blank=True, max_length=240, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Afectados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(10, 'DEPOSITO'), (20, 'GASTO'), (30, 'RETIRO'), (40, 'GASTO DEUDA'), (50, 'PAGO DEUDA')], default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cierre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.FloatField()),
                ('fin', models.FloatField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fechaInicio', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=70, null=True)),
                ('nombre', models.CharField(blank=True, max_length=130, null=True)),
                ('banco', models.CharField(blank=True, max_length=130, null=True)),
                ('saldo', models.FloatField(blank=True, null=True)),
                ('tipo', models.IntegerField(choices=[(40, 'DEUDA'), (30, 'CAJACHICA'), (10, 'BANCO')], default=10)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.IntegerField(blank=True, choices=[(10, 'CAJA CHICA'), (20, 'PROVEEDOR')], null=True)),
                ('formaPago', models.IntegerField(blank=True, choices=[(10, 'EFECTIVO'), (20, 'TARJETA'), (30, 'TRANSACCION'), (40, 'CHEQUE'), (50, 'DEPOSITO')], null=True)),
                ('proveedor', models.CharField(blank=True, max_length=140, null=True)),
                ('noDocumento', models.CharField(blank=True, max_length=140, null=True)),
                ('noComprobante', models.CharField(blank=True, max_length=140, null=True)),
                ('concepto', models.CharField(blank=True, max_length=240, null=True)),
                ('depositante', models.CharField(blank=True, max_length=240, null=True)),
                ('prestamo', models.BooleanField(default=False)),
                ('monto', models.FloatField()),
                ('saldo', models.FloatField(default=0)),
                ('fecha', models.DateField()),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('anulado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('representante', models.CharField(max_length=140)),
                ('fase', models.IntegerField(choices=[(10, 'INICIAL'), (20, 'ESTABLE')], default=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='movimiento',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='backend.Proyecto'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimiento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='deudor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='backend.Proyecto'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='backend.Proyecto'),
        ),
        migrations.AddField(
            model_name='cierre',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cierres', to='backend.Cuenta'),
        ),
        migrations.AddField(
            model_name='cierre',
            name='origen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.Movimiento'),
        ),
        migrations.AddField(
            model_name='afectados',
            name='cierre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='backend.Cierre'),
        ),
        migrations.AddField(
            model_name='afectados',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afectados', to='backend.Movimiento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cajachica',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.Cuenta'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='backend.Proyecto'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
