# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-29 00:04
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.hashers import make_password

def load_initial_data(apps, schema_editor):
    #Parte para la creación de un proyecto
    Proyecto = apps.get_model("backend","Proyecto")
    borderless = Proyecto(
        nombre="Borderless",
        representante="Borderless",
        fase=20
    )
    borderless.save()
    #Parte para la creación de una Caja chica
    Cuenta = apps.get_model("backend","Cuenta")
    cajachica = Cuenta(
        nombre="Borderless",
        numero="Caja chica",
        banco="Banco Industrial",
        proyecto=borderless,
        tipo=30
    )
    cajachica.save()
    #Parte para la creación de una Caja chica
    cuantaBanco = Cuenta(
        nombre="Borderless Guatemala, S.A.",
        numero="3990038097",
        banco="Banco Industrial",
        proyecto=borderless,
        tipo=10
    )
    cuantaBanco.save()
    #creacción de accesos
    # Permiso = apps.get_model("backend","Permiso")
    # access = Permiso(
    #     administrador=True,
    #     backoffice=False,
    #     supervisor=False,
    #     vendedor=False,
    #     bodeguero=False,
    #     compras=False,
    #     sin_acceso=False
    # )
    # access.save()
    #Creación de usuario admin
    Usuario = apps.get_model("backend","Usuario")
    user = Usuario(
        username="admin",
        first_name="Admin",
        last_name="Admin",
        proyecto= borderless,
        cajachica=cajachica,
        telefono="77889944",
        password="admin123",
        is_superuser=True,
        is_staff=1,
        permisos=100
    )
    user.password = make_password('admin123')
    user.save()
class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data)
    ]

