# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-30 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20181030_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierre',
            name='descripcion',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
