# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-01 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_cierre_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='destino',
            field=models.IntegerField(blank=True, choices=[(10, 'CAJA CHICA'), (20, 'PROVEEDOR'), (30, 'PROYECTO')], null=True),
        ),
    ]
