# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-03 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20181101_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fase',
            field=models.IntegerField(choices=[(10, 'INVESTIGACIÓN'), (20, 'EMPRESA')], default=20),
        ),
    ]
