# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-07 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20181103_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierre',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='cierrescuentas/%Y/%m/%d'),
        ),
    ]
