# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-07 21:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_cierre_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierre',
            name='usuarioCierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
