# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-12 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_cierre_usuariocierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierre',
            name='ext',
            field=models.CharField(choices=[('IMG', 'img'), ('PDF', 'pdf'), ('DOC', 'doc')], max_length=12, null=True),
        ),
    ]
