# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-13 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_cierre_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierre',
            name='ext',
            field=models.CharField(choices=[('img', 'img'), ('pdf', 'pdf'), ('doc', 'doc')], max_length=12, null=True),
        ),
    ]
