# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-14 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20181113_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='destino',
            field=models.IntegerField(blank=True, choices=[(10, 'CAJA CHICA'), (20, 'PROVEEDOR'), (30, 'PROYECTO'), (40, 'REINTEGRO')], null=True),
        ),
    ]
