# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-20 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_proyecto_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='subempresa',
            field=models.BooleanField(default=False),
        ),
    ]
