# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-21 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_proyecto_subempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.IntegerField(choices=[(50, 'SUBPROYECTO'), (40, 'DEUDA'), (30, 'CAJACHICA'), (10, 'BANCO')], default=10),
        ),
    ]
