# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-29 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_cierre_fechacierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='plazo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
