# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-01 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_movimiento_plazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='vehiculo',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='formaPago',
            field=models.IntegerField(blank=True, choices=[(10, 'EFECTIVO'), (20, 'TARJETA'), (30, 'TRANSACCION'), (40, 'CHEQUE'), (50, 'DEPOSITO'), (60, 'Guate ACH')], null=True),
        ),
    ]
