# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-05 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_proveedor_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fraccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimo_existencias', models.FloatField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('capacidad_maxima', models.FloatField(blank=True, null=True)),
                ('precio', models.FloatField()),
                ('precio2', models.FloatField(blank=True, null=True)),
                ('precio3', models.FloatField(blank=True, null=True)),
                ('vendible', models.BooleanField(default=True)),
                ('costo', models.FloatField(blank=True, null=True)),
                ('fecha_ultima_compra', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='backend.Fraccion')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('vendible', models.BooleanField(default=False)),
                ('tipo', models.IntegerField(choices=[(20, 'Fracción'), (30, 'A granel')])),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='backend.Proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='fraccion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fracciones', to='backend.Producto'),
        ),
    ]
