# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-05 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20181205_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='producto',
            name='multiplos',
            field=models.BooleanField(default=True),
        ),
    ]
