# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-05 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20181205_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraccion',
            name='capacidad_maxima',
            field=models.FloatField(default=1),
        ),
    ]
