# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-05 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20181205_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fraccion',
            old_name='nombre',
            new_name='presentacion',
        ),
    ]
