# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-10 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_auto_20181205_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='backend.Proveedor'),
        ),
    ]
