# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-10 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_auto_20181210_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo_caja',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
