# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-11 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_cuenta_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='moneda',
            field=models.CharField(choices=[('USD', 'USD'), ('GTQ', 'GTQ')], max_length=10),
        ),
    ]
