# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-12 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_auto_20181211_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='moneda',
            field=models.CharField(choices=[('USD', 'USD'), ('GTQ', 'GTQ')], default='GTQ', max_length=10),
        ),
    ]
