# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-11 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_auto_20181211_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrador', models.BooleanField(default=False)),
                ('backoffice', models.BooleanField(default=False)),
                ('supervisor', models.BooleanField(default=False)),
                ('vendedor', models.BooleanField(default=False)),
                ('bodeguero', models.BooleanField(default=False)),
                ('compras', models.BooleanField(default=False)),
                ('sin_acceso', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='permisos',
        ),
    ]
