# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-11 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_auto_20181211_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='accesos',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Permiso'),
        ),
    ]
