# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-12 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_auto_20181211_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='rol',
            new_name='puestos',
        ),
    ]
