# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-13 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_producto_moneda'),
        ('backend', '0037_auto_20181212_1802'),
    ]

    operations = [
    ]
