# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-13 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_merge_20181213_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='bodega_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='backend.Bodega'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='es_oc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='ingresado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='moneda',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('GTQ', 'GTQ')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='pago_automatico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='pago_completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='pagos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='backend.Movimiento'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='pendiente_pago',
            field=models.BooleanField(default=False),
        ),
    ]
