# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-13 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_auto_20181213_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_movimiento', to='backend.Movimiento')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_movimiento', to='backend.Fraccion')),
            ],
        ),
    ]
