# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-13 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_detallemovimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMovBodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadInicial', models.IntegerField()),
                ('cantidadActual', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='backend.Bodega')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='backend.Fraccion')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoBodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.IntegerField(choices=[(10, 'Ingreso'), (20, 'Salida'), (30, 'Despacho'), (40, 'Reajuste')])),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_bodega', to='backend.Bodega')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_bodega', to='backend.Movimiento')),
            ],
        ),
        migrations.AddField(
            model_name='detallemovbodega',
            name='movimiento_bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_mov_bodega', to='backend.MovimientoBodega'),
        ),
        migrations.AddField(
            model_name='detallemovbodega',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_mov_bodega', to='backend.Fraccion'),
        ),
    ]
