# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-13 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_detallemovimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='pagos',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento', to='backend.Movimiento'),
        ),
    ]
