# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-13 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_auto_20181213_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallemovbodega',
            name='cantidadActual',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
