# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-13 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_auto_20181213_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientobodega',
            name='movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_bodega', to='backend.Movimiento'),
        ),
    ]
