# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-14 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_auto_20181213_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallemovbodega',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_bodega', to='backend.Fraccion'),
        ),
    ]
