# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-14 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_auto_20181214_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobodega',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='backend.MovimientoBodega'),
        ),
    ]
