# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-14 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_auto_20181214_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobodega',
            name='justificacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
