# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-15 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_movimientobodega_justificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='bodega',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='stock',
        ),
        migrations.AddField(
            model_name='movimientobodega',
            name='vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
