# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-15 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_auto_20181213_1930'),
        ('backend', '0048_auto_20181215_1610'),
    ]

    operations = [
    ]
