# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-17 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_lineaproduccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobodega',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_bodega', to='backend.LineaProduccion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='porcentaje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
