# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-18 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_auto_20181217_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('lote', models.DateField()),
                ('justificacionAnulacion', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='backend.Bodega')),
            ],
        ),
        migrations.RemoveField(
            model_name='detallemovbodega',
            name='movimiento_bodega',
        ),
        migrations.RemoveField(
            model_name='movimientobodega',
            name='vencimiento',
        ),
        migrations.AddField(
            model_name='movimientobodega',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_bodega', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimientobodega',
            name='tipo',
            field=models.IntegerField(choices=[(10, 'Ingreso'), (30, 'Despacho'), (40, 'Reajuste'), (50, 'Baja')]),
        ),
        migrations.AddField(
            model_name='lote',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='backend.MovimientoBodega'),
        ),
        migrations.AddField(
            model_name='lote',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='backend.Lote'),
        ),
        migrations.AddField(
            model_name='detallemovbodega',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lote_detalle', to='backend.Lote'),
        ),
    ]
