# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-18 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_movimientobodega_justificacionanulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobodega',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='backend.Lote'),
        ),
    ]
