# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-18 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_movimientobodega_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobodega',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
