# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-19 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_detallemovbodega_movimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallemovbodega',
            old_name='cantidadActual',
            new_name='cantidad',
        ),
        migrations.AddField(
            model_name='detallemovbodega',
            name='cantidadFinal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
