# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-20 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_auto_20181219_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='movimiento',
        ),
        migrations.AddField(
            model_name='lote',
            name='movimiento',
            field=models.ManyToManyField(related_name='lotes', to='backend.MovimientoBodega'),
        ),
    ]
