# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-02 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_movimientobodega_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemovimiento',
            name='cantidadActual',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
