# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-03 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_detallemovimiento_cantidadactual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='vencimiento',
        ),
    ]
