# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-04 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0061_remove_lote_vencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='backend.Bodega')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='backend.Lote')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='backend.Fraccion')),
            ],
        ),
    ]
