# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-07 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobodega',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
