# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-04 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='caja_chica',
            field=models.BooleanField(default=False),
        ),
    ]
