# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-07 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_movimiento_caja_chica'),
        ('backend', '0063_movimientobodega_nota'),
    ]

    operations = [
    ]
