# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-09 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0066_auto_20190109_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='numero_oc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
