# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-09 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0065_auto_20190109_1456'),
        ('backend', '0066_auto_20190109_1452'),
    ]

    operations = [
    ]
