# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-10 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0067_merge_20190109_1736'),
        ('backend', '0067_movimiento_numero_oc'),
    ]

    operations = [
    ]
