# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-11 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0068_merge_20190110_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobodega',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costos_bodega', to='backend.Proyecto'),
        ),
    ]
