# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-11 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0069_movimientobodega_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemovbodega',
            name='cantidadActual',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
