# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-14 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0070_detallemovbodega_cantidadactual'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobodega',
            name='no_movimiento',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
