# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-15 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0072_inventario_costo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='costo',
            new_name='costo_total',
        ),
        migrations.AddField(
            model_name='inventario',
            name='costo_unitario',
            field=models.FloatField(default=0),
        ),
    ]
