# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-15 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0073_auto_20190115_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemovbodega',
            name='costo_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='detallemovbodega',
            name='costo_unitario',
            field=models.FloatField(default=0),
        ),
    ]
