# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-16 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0074_auto_20190115_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMovGranja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoGranja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[('Ingreso', 'Ingreso'), ('Baja', 'Baja'), ('Reajuste', 'Reajuste'), ('Peso', 'Peso')], default='Reajuste')),
                ('cantidad_gallinas', models.IntegerField(blank=True, null=True)),
                ('raza', models.CharField(blank=True, max_length=200, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('peso_gallinas', models.BooleanField(default=False)),
                ('promedio', models.FloatField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='es_gallinero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimientogranja',
            name='gallinero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_granja', to='backend.Proyecto'),
        ),
        migrations.AddField(
            model_name='movimientogranja',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_gallinero', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientogranja',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_granja', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallemovgranja',
            name='movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_movimiento', to='backend.MovimientoGranja'),
        ),
    ]
