# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-16 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0075_auto_20190116_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientogranja',
            name='tipo',
        ),
    ]
