# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-16 23:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0076_remove_movimientogranja_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granjas', to=settings.AUTH_USER_MODEL),
        ),
    ]
