# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-17 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0077_proyecto_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='cantidad_agua',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='cantidad_alimento',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
