# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-17 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0078_auto_20190117_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=240)),
                ('nit', models.CharField(max_length=240)),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
    ]
