# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-17 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0079_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='es_ov',
            field=models.BooleanField(default=False),
        ),
    ]
