# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-18 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0080_movimiento_es_ov'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Cliente'),
        ),
    ]
