# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-22 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0081_movimiento_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioMoneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_dolar', models.DateField()),
                ('cambio_dolar', models.FloatField()),
                ('fecha_yen', models.DateField()),
                ('cambio_yen_dolar', models.FloatField()),
                ('cambio_yen', models.FloatField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
