# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-22 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0082_auto_20190121_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientogranja',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
