# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-22 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0082_cambiomoneda'),
        ('backend', '0084_proyecto_fechainicio'),
    ]

    operations = [
    ]
