# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-22 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0085_merge_20190122_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='cliente',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='es_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
