# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-22 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0086_auto_20190122_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.IntegerField(choices=[(50, 'SUBPROYECTO'), (40, 'DEUDA'), (30, 'CAJACHICA'), (10, 'BANCO'), (60, 'Venta')], default=10),
        ),
    ]
