# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-22 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0087_auto_20190122_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='caja_venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caja_venta', to='backend.Cuenta'),
        ),
    ]
