# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-22 21:27
from __future__ import unicode_literals

from django.db import migrations

def create_cajaventa(apps, schema_editor):
    Usuario = apps.get_model("backend","Usuario")
    Cuenta = apps.get_model("backend","Cuenta")
    for usuario in Usuario.objects.all():
        nombre = "CVenta {}".format(usuario.first_name)
        banco = "{}-CV-{}".format(usuario.proyecto.nombre, usuario.first_name)
        cuentaVenta = Cuenta.objects.create(
            numero=nombre,
            nombre=nombre,
            banco="Caja de Venta",
            proyecto=usuario.proyecto,
            moneda='GTQ',
            tipo=60
        )
        cuentaVenta.save()
        usuario.caja_venta = cuentaVenta
        usuario.save()

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0088_usuario_caja_venta'),
    ]

    operations = [
        migrations.RunPython(create_cajaventa)
    ]
    
