# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-22 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0089_auto_20190122_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='caja_venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caja_venta', to='backend.Cuenta'),
        ),
    ]
