# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-22 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0090_auto_20190122_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afectados',
            name='tipo',
            field=models.IntegerField(choices=[(10, 'DEPOSITO'), (20, 'GASTO'), (30, 'RETIRO'), (40, 'GASTO DEUDA'), (50, 'PAGO DEUDA'), (70, 'Venta')], default=20),
        ),
    ]
