# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-24 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0091_auto_20190122_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='movimientoPrestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='backend.Movimiento'),
        ),
    ]
