# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-24 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0092_cuenta_movimientoprestamo'),
        ('backend', '0092_movimiento_despacho_inmediato'),
    ]

    operations = [
    ]
