# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-27 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0093_merge_20190124_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobodega',
            name='tipoDespacho',
            field=models.IntegerField(blank=True, choices=[(10, 'Despacho a línea'), (20, 'Despacho a venta'), (30, 'Despacho a bodega')], null=True),
        ),
        migrations.AddField(
            model_name='movimientobodega',
            name='tipoIngreso',
            field=models.IntegerField(blank=True, choices=[(10, 'Ingreso desde línea'), (30, 'Ingreso desde compra'), (20, 'Ingreso desde bodega')], null=True),
        ),
    ]
