# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-28 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0094_auto_20190127_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preciofraccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(choices=[('USD', 'USD'), ('GTQ', 'GTQ')], max_length=10)),
                ('precio', models.FloatField()),
                ('activo', models.BooleanField(default=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='backend.Fraccion')),
            ],
        ),
    ]
