# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-28 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0096_auto_20190128_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraccion',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
