# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-28 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0097_auto_20190128_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraccion',
            name='precioUSD',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fraccion',
            name='precioUSD2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fraccion',
            name='precioUSD3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
