# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-29 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0098_auto_20190128_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='cuentaAcreedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deudas_acreedor', to='backend.Cuenta'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cuentaDeudor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deudas_deudor', to='backend.Cuenta'),
        ),
    ]
