# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-30 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0099_auto_20190129_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='backend.Proyecto'),
        ),
        migrations.AddField(
            model_name='lote',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='backend.LineaProduccion'),
        ),
    ]
