# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-31 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0101_auto_20190131_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='precioUnitario',
            field=models.FloatField(default=0),
        ),
    ]
