# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-01 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0105_movimiento_tiene_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='pl',
            field=models.IntegerField(blank=True, choices=[(21, 'Puro'), (22, 'PPC'), (23, 'Sistema de costos de diseño'), (24, 'Gastos promocionales'), (25, 'Tarifa de uso del sistema'), (26, 'Otros (distribución de muestras, implementación de eventos, etc.)'), (27, 'Coste de consignación del servicio de respaldo (creativo, relaciones públicas, etc.)'), (28, 'Transporte domestico'), (30, 'Consumibles / gastos mensuales (aquellos directamente relacionados con las operaciones comerciales)'), (31, 'Transporte de importación / exportación en el extranjero (distinto del costo)'), (32, 'Telefono, internet'), (33, 'Otros gastos de comunicación (sellos etc.)'), (34, 'Sueldo pago'), (35, 'Trabajo a tiempo parcial a corto plazo'), (36, 'Gastos de viaje (ajuste de gastos)'), (37, 'Gastos de transporte de cercanías'), (38, 'Gastos legales de bienestar'), (40, 'Costo de reclutamiento'), (41, 'Costo de desarrollo del producto / servicio'), (42, 'Comisión bancaria'), (43, 'Comisión de corretaje'), (44, 'Otra cuota de pago'), (45, 'Alquiler de alquiler, servicios públicos de calefacción, tarifa de comunicación'), (46, 'Gastos de suministros de oficina'), (47, 'Bienestar social'), (48, 'Costo de reparacion'), (51, 'Retención de impuestos'), (52, 'Impuesto'), (53, 'Otros')], null=True),
        ),
    ]
