# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-01 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0106_auto_20190201_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fechaFinal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='monto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='plazo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
