# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-01 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0106_auto_20190201_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='fecha_inicio_recuperacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
