# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-01 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0107_movimiento_fecha_inicio_recuperacion'),
        ('backend', '0107_auto_20190201_2255'),
    ]

    operations = [
    ]
