# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-02 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0108_merge_20190201_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_inicio_costo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
