# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-02 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0109_proyecto_fecha_inicio_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='fecha_final_recuperacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
