# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-29 00:04
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.hashers import make_password

def load_initial_data(apps, schema_editor):
    Permiso = apps.get_model("backend","Permiso")
    access = Permiso(
        administrador=True,
        backoffice=False,
        supervisor=False,
        vendedor=False,
        bodeguero=False,
        compras=False,
        sin_acceso=False
    )
    access.save()
    Usuario = apps.get_model("backend","Usuario")
    primer_user = Usuario.objects.get(id=1)
    primer_user.accesos = access
    primer_user.puestos=100
    primer_user.save()
class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0110_movimiento_fecha_final_recuperacion'),
    ]

    operations = [
        migrations.RunPython(load_initial_data)
    ]
