# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-05 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0111_auto_20190204_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='categoria_recuperacion',
            field=models.IntegerField(choices=[(159, 'Depreciación'), (160, 'Depreciación sistemas')], default=159),
        ),
    ]
