# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-07 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0113_proyecto_categoria_recuperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='descuento',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='cf',
            field=models.IntegerField(blank=True, choices=[(1, 'Ventas en efectivo'), (2, 'Cuentas por cobrar'), (3, 'Pago anticipado'), (4, 'Depósito de garantía'), (5, 'Otro efectivo / cuentas por cobrar'), (6, 'Compra en efectivo'), (7, 'Cuentas por pagar por pagar'), (8, 'Pago acumulado'), (9, 'Gastos pagados por adelantado'), (10, 'Venta, administracion'), (11, 'Otras compras / ventas y pago de gastos administrativos.'), (12, 'Tiendas · Edificios'), (13, 'Maquinaria · Accesorios · Vehículo'), (14, 'Construcción en progreso'), (15, 'Construcción de software en progreso'), (16, 'Depósito de seguridad / depósito de seguridad'), (17, 'Capital'), (18, 'Otros financiados'), (19, 'Adquisición de préstamos'), (20, 'Reembolso de la deuda (incluidos los intereses)'), (54, 'Ajuste de depósito intergrupal')], null=True),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='pl',
            field=models.IntegerField(blank=True, choices=[(21, 'Puro'), (22, 'PPC'), (23, 'Sistema de costos de diseño'), (24, 'Gastos promocionales'), (25, 'Tarifa de uso del sistema'), (26, 'Otros (distribución de muestras, implementación de eventos, etc.)'), (27, 'Coste de consignación del servicio de respaldo (creativo, relaciones públicas, etc.)'), (28, 'Transporte domestico'), (30, 'Consumibles / gastos mensuales (aquellos directamente relacionados con las operaciones comerciales)'), (31, 'Transporte de importación / exportación en el extranjero (distinto del costo)'), (32, 'Telefono, internet'), (33, 'Otros gastos de comunicación (sellos etc.)'), (34, 'Sueldo pago'), (35, 'Trabajo a tiempo parcial a corto plazo'), (36, 'Gastos de viaje (ajuste de gastos)'), (37, 'Gastos de transporte de cercanías'), (38, 'Gastos legales de bienestar'), (40, 'Costo de reclutamiento'), (41, 'Costo de desarrollo del producto / servicio'), (42, 'Comisión bancaria'), (43, 'Comisión de corretaje'), (44, 'Otra cuota de pago'), (45, 'Alquiler de alquiler, servicios públicos de calefacción, tarifa de comunicación'), (46, 'Gastos de suministros de oficina'), (47, 'Bienestar social'), (48, 'Costo de reparacion'), (51, 'Retención de impuestos'), (52, 'Impuesto'), (53, 'Otros'), (55, 'Comisión de ventas'), (56, 'Tasa de liquidación')], null=True),
        ),
    ]
