# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-12 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0115_auto_20190208_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
