# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-12 17:42
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Q

def load_initial_data(apps, schema_editor):
    Cuenta = apps.get_model("backend","Cuenta")
    Cuenta.objects.filter(Q(tipo=60) | Q(tipo=30)).update(moneda='GTQ')
    #Se filtra las cajas de venta y cajas chicas
    #y les asigna una moneda para que se sepa que mondeda
    #se maneja el dinero en este tipo de cuentas

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0116_proveedor_descripcion'),
    ]

    operations = [
        migrations.RunPython(load_initial_data)
    ]
