# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-20 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0120_proveedor_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoproveedor',
            name='correo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactoproveedor',
            name='puesto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
