# Generated by Django 2.2 on 2019-04-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0121_auto_20190320_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallemovbodega',
            name='activo',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='detallemovgranja',
            name='activo',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='activo',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='activo',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='movimientobodega',
            name='activo',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
