# Generated by Django 2.2 on 2019-04-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0122_auto_20190416_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierre',
            name='fechaInicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
