# Generated by Django 2.2 on 2019-05-01 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0123_auto_20190430_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='encargado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bodega', to=settings.AUTH_USER_MODEL),
        ),
    ]
