# Generated by Django 2.2 on 2019-05-06 22:31

from django.db import migrations


def _method(apps, schema_editor):
    """ Intento fix pagos """
    Movimiento = apps.get_model("backend", "Movimiento")

    # Ventas que se marcaron como despacho inmediato
    ventas = Movimiento.objects.filter(es_ov=True, activo=True, anulado=False, despacho_inmediato=True)
    # Alterar las ventas para marcar como entregado
    for venta in ventas:
        venta.ingresado = True
        venta.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0124_bodega_encargado'),
    ]

    operations = [
        migrations.RunPython(_method, reverse_code=migrations.RunPython.noop),
    ]
