# Generated by Django 2.2 on 2019-05-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0126_auto_20190510_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierre',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cierre',
            name='justificacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
