# Generated by Django 2.2 on 2019-05-14 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0127_auto_20190513_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierre',
            name='origen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cierre_prestamo', to='backend.Movimiento'),
        ),
    ]
