# Generated by Django 2.2 on 2019-06-06 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0128_auto_20190513_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemovbodega',
            name='movimiento_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_presentacion', to='backend.MovimientoBodega'),
        ),
    ]
