# Generated by Django 2.2 on 2019-07-03 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0129_detallemovbodega_movimiento_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierre',
            name='movimiento_cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cierre_venta', to='backend.Movimiento'),
        ),
    ]
