# Generated by Django 2.2 on 2020-06-24 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0130_cierre_movimiento_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='deposito',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='ventas_ids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimiento_hijo', to='backend.Movimiento'),
        ),
    ]
