# Generated by Django 2.2 on 2020-06-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0132_auto_20200624_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='cierre_ventas',
            field=models.BooleanField(default=False),
        ),
    ]
