# Generated by Django 2.2 on 2020-07-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0133_movimiento_cierre_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientogranja',
            name='insumos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientogranja',
            name='medicina',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientogranja',
            name='porcion_agua',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientogranja',
            name='porcion_alimento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientogranja',
            name='precio_carton',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientogranja',
            name='precio_concentrado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientogranja',
            name='salario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientogranja',
            name='semana',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
