# Generated by Django 2.2 on 2020-07-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0134_auto_20200704_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientogranja',
            name='insumos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientogranja',
            name='medicina',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientogranja',
            name='porcion_agua',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientogranja',
            name='porcion_alimento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientogranja',
            name='precio_carton',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientogranja',
            name='precio_concentrado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientogranja',
            name='salario',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
