# Generated by Django 2.2 on 2020-07-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0137_auto_20200706_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientogranja',
            name='postura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientogranja',
            name='posturaG',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
