# Generated by Django 2.2 on 2020-07-08 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0138_auto_20200708_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientogranja',
            name='postura',
        ),
    ]
