# Generated by Django 2.2 on 2020-07-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0139_remove_movimientogranja_postura'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientogranja',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientogranja',
            name='edad_inicial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientogranja',
            name='fecha_inicial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
