# Generated by Django 2.2 on 2020-07-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0140_auto_20200709_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientogranja',
            name='fecha_inicial',
            field=models.DateField(blank=True, null=True),
        ),
    ]
