# Generated by Django 2.2 on 2020-07-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0141_auto_20200709_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientogranja',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='movimientogranja',
            name='semana',
        ),
    ]
