# Generated by Django 2.2 on 2020-07-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0142_auto_20200710_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientogranja',
            name='produccion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientogranja',
            name='rentabilidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientogranja',
            name='venta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
