# Generated by Django 2.2 on 2020-07-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0143_auto_20200713_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientogranja',
            name='postura',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
