# Generated by Django 2.2 on 2020-08-20 16:16

from django.db import migrations

from backend.models import Fraccion, Preciofraccion


class Migration(migrations.Migration):

    def registroo(apps, schema_editor):
        fracciones = Fraccion.objects.filter(activo=True, vendible=True).order_by('capacidad_maxima')

        for fraaaa in fracciones:

            if fraaaa.precio is not None and fraaaa.precio > 0:
                Preciofraccion.objects.create(
                    moneda=Preciofraccion.QUETZAL,
                    precio=fraaaa.precio, stock=fraaaa, activo=True
                )
            if fraaaa.precio2 is not None and fraaaa.precio2 > 0:
                Preciofraccion.objects.create(
                    moneda=Preciofraccion.QUETZAL,
                    precio=fraaaa.precio2, stock=fraaaa, activo=True
                )
            if fraaaa.precio3 is not None and fraaaa.precio3 > 0:
                Preciofraccion.objects.create(
                    moneda=Preciofraccion.QUETZAL,
                    precio=fraaaa.precio3, stock=fraaaa, activo=True
                )
            if fraaaa.precioUSD is not None and fraaaa.precioUSD > 0:
                Preciofraccion.objects.create(
                    moneda=Preciofraccion.DOLAR,
                    precio=fraaaa.precioUSD, stock=fraaaa, activo=True
                )
            if fraaaa.precioUSD2 is not None and fraaaa.precioUSD2 > 0:
                Preciofraccion.objects.create(
                    moneda=Preciofraccion.DOLAR,
                    precio=fraaaa.precioUSD2, stock=fraaaa, activo=True
                )
            if fraaaa.precioUSD3 is not None and fraaaa.precioUSD3 > 0:
                Preciofraccion.objects.create(
                    moneda=Preciofraccion.DOLAR,
                    precio=fraaaa.precioUSD3, stock=fraaaa, activo=True
                )

    dependencies = [
        ('backend', '0146_auto_20200804_1426'),
    ]

    operations = [
        migrations.RunPython(registroo)
    ]
