# Generated by Django 2.2 on 2021-01-26 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0147_migracion_precios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='backend.Proyecto'),
        ),
    ]
