# Generated by Django 2.2 on 2021-04-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0148_auto_20210126_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallemovimiento',
            name='precio_costo',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=18),
        ),
    ]
